// Minimal dress code clothing data for Lambda use — derived from src/data/dressCodes.ts
// Do not add UI/photo/women data here.

export const DRESS_CODE_ITEMS: Record<string, string[]> = {
  'white-tie': [
    'Black wool tailcoat with silk-faced lapels',
    'White piqué wing-collar dress shirt with white piqué waistcoat',
    'Black dress trousers with double silk braid down each leg',
    'White piqué bow tie',
    'White pocket square',
    'Cufflinks',
    'Patent leather Oxford or court shoe',
  ],
  'black-tie': [
    'Black wool or barathea dinner jacket with silk-faced lapels',
    'White dress shirt with pleated front or marcella bib',
    'Black dress trousers with single silk braid',
    'Black silk bow tie',
    'Black cummerbund or matching waistcoat',
    'Cufflinks and dress studs',
    'Black patent leather Oxford or pump',
  ],
  'black-tie-optional': [
    'Black dinner jacket or dark business suit',
    'White dress shirt or formal shirt',
    'Matching trousers',
    'Black bow tie or conservative necktie',
    'Leather Oxford or Derby shoe',
  ],
  'morning-dress': [
    'Morning coat or black tailcoat with tails',
    'Waistcoat in dove grey or buff',
    'Striped morning trousers',
    'Cravat or formal necktie',
    'Top hat',
    'Black Oxford shoe',
  ],
  'creative-black-tie': [
    'Dinner jacket — classic or statement (velvet, patterned, coloured)',
    'Formal or fashion-forward dress shirt',
    'Dress trousers matching jacket',
    'Statement bow tie or necktie',
    'Derby, Chelsea boot, or classic dress shoe',
  ],
  'smart-elegant': [
    'Tailored dark or navy suit with fashion-forward cut or blazer',
    'Quality dress shirt — white, ecru, or deep colour',
    'Matching well-cut tailored trousers',
    'Silk pocket square',
    'Oxford, loafer, or sleek Derby shoe',
  ],
  'cocktail': [
    'Dark suit jacket',
    'White or pale dress shirt',
    'Matching suit trousers',
    'Silk or quality necktie',
    'Black Oxford or Derby shoe',
  ],
  'festive': [
    'Velvet blazer or deep-coloured festive suit jacket',
    'Quality dress shirt or festive patterned shirt',
    'Dark suit trousers or smart chinos',
    'Festive tie or bow tie in seasonal colour',
    'Oxford, Derby, or Chelsea boot',
  ],
  'lounge-suit': [
    'Tailored suit jacket',
    'Dress shirt — white, pale blue, or subtle pattern',
    'Matching suit trousers',
    'Leather belt matching shoes',
    'Oxford or Derby shoe',
  ],
  'business-formal': [
    'Dark conservative suit jacket (charcoal, navy, dark grey)',
    'White or light blue dress shirt',
    'Matching suit trousers',
    'Conservative silk necktie',
    'Black Oxford shoe',
  ],
  'business-casual': [
    'Blazer or smart sport coat',
    'Polo shirt or button-down shirt',
    'Chinos or pressed trousers (no jeans)',
    'Leather loafer, brogue, or Chelsea boot',
  ],
  'garden-party': [
    'Linen suit jacket or unstructured blazer in light tone',
    'Open-collar linen, chambray, or Oxford shirt',
    'Linen or cotton trousers in cream, grey, or pale blue',
    'Floral or pastel pocket square',
    'Leather loafer, suede Derby, or smart espadrille',
  ],
  'apres-ski': [
    'Cashmere or wool sweater or smart down gilet over shirt',
    'Fine-knit roll neck or quality flannel shirt',
    'Dark smart jeans or tailored cord trousers',
    'Quality watch',
    'Après boot, smart ankle boot, or luxury snow boot',
  ],
  'country-house': [
    'Tweed sport coat, check blazer, or Barbour wax jacket',
    'Tattersall check or Oxford cloth shirt',
    'Corduroy, moleskin, or chino trousers in earthy tones',
    'Woollen tie or cravat (optional)',
    'Country brogue, Derby, or chelsea boot in brown or tan',
  ],
  'smart-casual': [
    'Blazer or structured jacket',
    'Quality shirt, polo, or fine-knit sweater',
    'Dark jeans, chinos, or casual trousers',
    'Smart leather trainer, loafer, or Chelsea boot',
  ],
  'resort-casual': [
    'Linen or lightweight casual shirt',
    'Linen, cotton, or linen-blend trousers or shorts',
    'Leather sandal or casual loafer',
  ],
  'casual': [
    'T-shirt, casual shirt, or lightweight sweater',
    'Jeans, chinos, or casual trousers',
    'Trainer, canvas shoe, or casual boot',
  ],
};

export const DRESS_CODE_NAMES: Record<string, string> = {
  'white-tie': 'White Tie',
  'black-tie': 'Black Tie',
  'black-tie-optional': 'Black Tie Optional',
  'morning-dress': 'Morning Dress',
  'smart-elegant': 'Smart Elegant',
  'creative-black-tie': 'Creative Black Tie',
  'cocktail': 'Cocktail Attire',
  'festive': 'Festive Attire',
  'lounge-suit': 'Lounge Suit',
  'business-formal': 'Business Formal',
  'business-casual': 'Business Casual',
  'garden-party': 'Garden Party',
  'apres-ski': 'Après-Ski',
  'country-house': 'Country House',
  'smart-casual': 'Smart Casual',
  'resort-casual': 'Resort / Outdoor Casual',
  'casual': 'Casual',
};
